name: CI 

on:
  [pull_request, push]

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run tests
        run: go test ./...

      - name: Gosec - Check for vulnerable code 
        run: gosec ./...

  format:
    name: Format Go
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Go format
        run: test -z $(go fmt ./...)

      - name: Format Go imports
        run: test -z $(goimports-revisor ./... -test-diff)

      - name: Run staticcheck
        run: staticcheck ./...

